on: workflow_dispatch
jobs:
  build:
    runs-on: windows-2025
    steps:
      - run: curl -O https://vcgit.hhi.fraunhofer.de/jvet/JM/-/archive/JM-19.1/JM-JM-19.1.zip
      - run: tar -xf JM-JM-19.1.zip
      - run: cmake -S JM-JM-19.1 -B build -A x64
      - run: cmake --build build --config Release
      - uses: actions/upload-artifact@v4
        with:
          path: JM-JM-19.1/bin/vs17/msvc-19.44/x86_64/release
