on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    steps:
      - run: |
          curl -O https://vcgit.hhi.fraunhofer.de/jvet/JM/-/archive/master/JM-master.zip
          tar -xf JM-master.zip
          cmake -S JM-master -B build -A x64
          cmake --build build --config Release
      - uses: actions/upload-artifact@master
        with:
          path: JM-master/bin/vs18/msvc-19.50/x86_64/release
