on: workflow_dispatch
jobs:
  build:
    runs-on: windows-2025
    steps:
      - run: |
          curl -O https://vcgit.hhi.fraunhofer.de/jvet/VVCSoftware_VTM/-/archive/VTM-23.11/VVCSoftware_VTM-VTM-23.11.zip
          tar -xf VVCSoftware_VTM-VTM-23.11.zip
          cmake -S VVCSoftware_VTM-VTM-23.11 -B build -A x64
          cmake --build build --config Release
          Copy-Item C:\Program Files\OpenSSL-Win64\bin\libcrypto-3-x64.dll -Destination VVCSoftware_VTM-VTM-23.11/bin/vs17/msvc-19.44/x86_64/release
          Copy-Item C:\Program Files\OpenSSL-Win64\bin\libssl-3-x64.dll -Destination VVCSoftware_VTM-VTM-23.11/bin/vs17/msvc-19.44/x86_64/release
#          curl -O https://vcgit.hhi.fraunhofer.de/jvet/JM/-/archive/JM-19.1/JM-JM-19.1.zip
#          tar -xf JM-JM-19.1.zip
#          cmake -S JM-JM-19.1 -B build -A x64
      - uses: actions/upload-artifact@v4
        with:
          path: VVCSoftware_VTM-VTM-23.11/bin/vs17/msvc-19.44/x86_64/release
#          path: JM-JM-19.1/bin/vs17/msvc-19.44/x86_64/release
