on: workflow_dispatch
jobs:
  build:
    runs-on: windows-2025
    steps:
      - run: |
          curl -O https://vcgit.hhi.fraunhofer.de/ecm/ECM/-/archive/ECM-18.0/ECM-ECM-18.0.zip
          tar -xf ECM-ECM-18.0.zip
          cmake -S ECM-ECM-18.0 -B build -A x64 -DENABLE_SEARCH_OPENSSL=off
          cmake --build build --config Release
      - uses: actions/upload-artifact@v4
        with:
          path: ECM-ECM-18.0/bin/vs17/msvc-19.44/x86_64/release
